Fix clang compilation error
main/WebServer.cpp:16184:103: error: cannot pass non-trivial object of type 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char>>') to variadic method; expected type from format string was 'char *' [-Wnon-pod-varargs]
                                _log.Log(LOG_ERROR, "Parameter sensorarea missing with groupby '%s'", sgroupby);
                                                                                                ~~    ^~~~~~~~
main/WebServer.cpp:16184:103: note: did you mean to call the c_str() method?
                                _log.Log(LOG_ERROR, "Parameter sensorarea missing with groupby '%s'", sgroupby);
                                                                                                      ^
                                                                                                              .c_str()