private - public
because off Error;

/hardware/Netatmo.h:20:36: error: ‘_eNetatmoType’ does not name a type; did you mean ‘_eMeterType’?

I have put the private declaration first.