hardware/openzwave/Manager.h: fix build with latest openzwave
openzwave in version 1.6 added an optional _pos parameter to
GetValueHelp and GetValueLabel, as a result link fails on:

OpenZWave.cpp:(.text+0x63bc): undefined reference to `OpenZWave::Manager::GetValueHelp[abi:cxx11](OpenZWave::ValueID const&)'

To fix this error, update hardware/openzwave/Manager.h but a better
solution would be to use the headers provided by openzwave instead of
including them in domoticz. However, this would be a major change.

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>